### PR TITLE
add: mock request instead of starting a service

### PR DESCRIPTION
**Pull request by Ignorant-lxf**

### CODE REVIEW

**Comment by Aoang** [comment]
I don't understand what this is doing. Why do you need to import http package, what are its functions?

**Comment by Ignorant-lxf** [comment]
> I don't understand what this is doing. Why do you need to import http package, what are its functions?

My idea is passing a httpRequest as param to a method,then return a httpResponse.And the serve established rely on the method.

In that method,according params to create a complete request,using fasthttp.Server.ServeConn() to handle request.

Refer to https://github.com/gofiber/fiber/blob/master/app.go#L868.

**Comment by Aoang** [comment]
You are testing http, what does it have to do with THz?

**Comment by Ignorant-lxf** [comment]
> You are testing http, what does it have to do with THz?

In this case,I don't need to care about the occupied of port.

Otherwise,I think it's better convient than start a service.

**Comment by Aoang** [comment]
Why not?
https://github.com/valyala/fasthttp/blob/d404f2db91fcf59244f75272ceaa1d28d9ff352c/server_test.go#L37-L80

**Comment by Ignorant-lxf** [comment]
nothing to do

**Pull request closed without merging**
